### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by pi8027** [math-comp/algebra-tactics#52]
TODOs:
- [x] #51,
- [x] #53: ~fix~ remove `mathcomp:1.14.0-coq-dev` CI job,
- [x] #55: remove debug prints (related to #46),
- [x] merge #35 as a demo file explaining the techniques behind Algebra Tactics,
- [x] #58: test cases for the use of `exact_no_check`.

**Comment by pi8027** [comment]
Done.
